site_name: Denali MC Help
site_url: https://www.mkdocs.org
site_description: Help for Denali MC (The minecraft server)
site_author: Connor Slade

repo_url: https://github.com/Basicprogrammer10/Denali-MC-Help/
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md

copyright: Copyright &copy; 2020 , Connor SLade

plugins:
    - search
